# Generated by Django 5.2.4 on 2025-08-10 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('nom_du_prof_charger', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('durer_cours', models.DateField()),
                ('modules', models.CharField(choices=[('premier', 'Module 1'), ('second', 'Module 2')], max_length=10)),
                ('progression', models.IntegerField(default=0)),
                ('suivi', models.BooleanField(default=True)),
            ],
            options={
                'permissions': [('peut_ajouter_cours', 'Peut ajouter un cours'), ('peut_supprimer_cours', 'Peut supprimer un cours'), ('peut_modifier_cours', 'Peut modifier un cours'), ('peut_suivre_cours', 'Peut suivre un cours')],
            },
        ),
        migrations.CreateModel(
            name='Lecon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('chapitre', models.CharField(choices=[('A', 'ab'), ('B', 'bb')], max_length=10)),
                ('description', models.TextField()),
                ('lien_synchrone', models.URLField(blank=True, null=True)),
                ('date_de_creation', models.DateTimeField(auto_now_add=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecons', to='cours.cours')),
            ],
            options={
                'permissions': [('peut_ajouter_lecon', 'Peut ajouter une lecon'), ('peut_supprimer_lecon', 'Peut supprimer une lecon'), ('peut_modifier_lecon', 'Peut modifier une lecon'), ('peut_suivre_lecon', 'Peut suivre une lecon')],
            },
        ),
    ]
