# Generated by Django 5.2.4 on 2025-08-04 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('nom_du_prof_charger', models.CharField()),
                ('description', models.TextField()),
                ('durer_cours', models.DateField()),
                ('modules', models.CharField(choices=[('premier', 'Module 1'), ('Second', 'module 2')])),
                ('progression', models.IntegerField(default=0)),
                ('lien_synchrone', models.URLField(blank=True, null=True)),
                ('suivi', models.BooleanField(default=True)),
            ],
            options={
                'permissions': [('peut_ajouter_cours', 'Peut ajouter un cours'), ('peut_supprimer_cours', 'Peut supprimer un cours'), ('peut_modifier_cours', 'Peut modifier un cours'), ('peut_suivre_cours', 'Peut suivre un cours')],
            },
        ),
        migrations.CreateModel(
            name='Lecon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('chapitre', models.CharField(choices=[('A', 'ab'), ('B', 'bb')])),
                ('description', models.TextField()),
                ('lien_synchrone', models.URLField(blank=True, null=True)),
            ],
            options={
                'permissions': [('peut_ajouter_lecon', 'Peut ajouter une lecon'), ('peut_supprimer_lecon', 'Peut supprimer une lecon'), ('peut_modifier_lecon', 'Peut modifier une lecon'), ('peut_suivre_lecon', 'Peut suivre une lecon')],
            },
        ),
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('lecon', models.CharField(max_length=100)),
                ('suivi', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('point_controle_link', models.URLField(blank=True)),
                ('pdf1', models.URLField(blank=True)),
                ('pdf2', models.URLField(blank=True)),
                ('video1', models.URLField(blank=True)),
                ('video2', models.URLField(blank=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapitres', to='cours.cours')),
            ],
        ),
    ]
