# Generated by Django 5.2.4 on 2025-08-11 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecon',
            name='cours',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lecons', to='cours.cours'),
        ),
    ]
