# Generated by Django 5.2.4 on 2025-08-05 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField()),
                ('description', models.CharField()),
            ],
        ),
        migrations.DeleteModel(
            name='Chapitre',
        ),
    ]
