# Generated by Django 5.2.4 on 2025-08-12 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0002_alter_lecon_cours'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecon',
            name='pdf1',
            field=models.FileField(default=12, upload_to='pdfs/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecon',
            name='pdf2',
            field=models.FileField(default=1, upload_to='pdfs/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecon',
            name='video1',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='lecon',
            name='video2',
            field=models.URLField(blank=True),
        ),
    ]
