# Generated by Django 5.2.4 on 2025-08-05 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0002_departement_delete_chapitre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Departement',
        ),
    ]
