# Generated by Django 5.2.4 on 2025-08-12 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0003_lecon_pdf1_lecon_pdf2_lecon_video1_lecon_video2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecon',
            name='cours',
        ),
    ]
