# Generated by Django 5.2.4 on 2025-08-16 22:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0007_alter_devoir_note_alter_evaluation_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devoir',
            name='date_limite',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='date_limite',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='nombre_essaie',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
