# Generated by Django 5.2.4 on 2025-08-19 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0010_evaluation_questionnaires_question_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
