# Generated by Django 5.2.4 on 2025-08-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0011_question_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='texte',
            new_name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='reponse',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
