# Generated by Django 5.2.4 on 2025-08-11 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='departement',
            field=models.CharField(choices=[('Economie', 'Economie'), ('Dev_comunautaire', 'Dev_comunautaire'), ('Droit', 'Droit'), ('Latice', 'Latice'), ('Divers', 'Divers'), ('Remforcement', 'Remforcement des capacités')], max_length=100),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='groupe',
            field=models.CharField(choices=[('A', 'Groupe A'), ('B', 'Groupe B')], max_length=1),
        ),
    ]
