# Generated by Django 5.2.4 on 2025-08-04 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cours',
            options={'permissions': [('peut_ajouter_cours', 'Peut ajouter un cours'), ('peut_supprimer_cours', 'Peut supprimer un cours'), ('peut_modifier_cours', 'Peut modifier un cours'), ('peut_suivre_cours', 'Peut suivre un cours')]},
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='cours',
        ),
    ]
