# Generated by Django 5.2.4 on 2025-08-04 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0002_alter_cours_options_remove_etudiant_cours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('chapitre', models.CharField(choices=[('A', 'ab'), ('B', 'bb')])),
                ('description', models.TextField()),
                ('lien_synchrone', models.URLField(blank=True, null=True)),
            ],
            options={
                'permissions': [('peut_ajouter_lecon', 'Peut ajouter une lecon'), ('peut_supprimer_lecon', 'Peut supprimer une lecon'), ('peut_modifier_lecon', 'Peut modifier une lecon'), ('peut_suivre_lecon', 'Peut suivre une lecon')],
            },
        ),
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('lecon', models.CharField(max_length=100)),
                ('suivi', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('point_controle_link', models.URLField(blank=True)),
                ('pdf1', models.URLField(blank=True)),
                ('pdf2', models.URLField(blank=True)),
                ('video1', models.URLField(blank=True)),
                ('video2', models.URLField(blank=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapitres', to='etudiants.cours')),
            ],
        ),
    ]
