# Generated by Django 5.2.4 on 2025-08-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0002_alter_etudiant_departement_alter_etudiant_groupe'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='telephone',
            field=models.CharField(default=3456, max_length=18),
            preserve_default=False,
        ),
    ]
