# Generated by Django 5.2.4 on 2025-08-04 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0003_lecon_chapitre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapitre',
            name='cours',
        ),
        migrations.DeleteModel(
            name='Lecon',
        ),
        migrations.DeleteModel(
            name='Chapitre',
        ),
        migrations.DeleteModel(
            name='Cours',
        ),
    ]
