# Generated by Django 5.2.4 on 2025-08-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0003_etudiant_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='photo',
            field=models.ImageField(default=12, upload_to=''),
            preserve_default=False,
        ),
    ]
